### ISSUE TITLE
Empty files in fileadmin/introduction

### ISSUE THREAD

**Issue by ohader** [FriendsOfTYPO3/introduction#13] opened 2018-09-26 21:33 UTC
* TYPO3 v9.4.0
* Introduction Package master (bde11d6787dc4731442519aa1d6acd6b0147d80e)

```
$ find fileadmin/introduction -type f -size 0

fileadmin/introduction/audio/typo3-still-here.mp3
fileadmin/introduction/audio/what-is-typo3.mp3
fileadmin/introduction/images/background/background-grey.jpg
fileadmin/introduction/images/background/background-orange.jpg
fileadmin/introduction/images/content/content-accordion.png
fileadmin/introduction/images/content/content-bullets.png
fileadmin/introduction/images/content/content-carousel.png
fileadmin/introduction/images/content/content-elements-login.png
fileadmin/introduction/images/content/content-elements-mailform.png
fileadmin/introduction/images/content/content-elements-searchform.png
fileadmin/introduction/images/content/content-header.png
fileadmin/introduction/images/content/content-image.png
fileadmin/introduction/images/content/content-menu-abstract.png
fileadmin/introduction/images/content/content-menu-categorized.png
fileadmin/introduction/images/content/content-menu-pages.png
fileadmin/introduction/images/content/content-menu-recently-updated.png
fileadmin/introduction/images/content/content-menu-related.png
fileadmin/introduction/images/content/content-menu-section.png
fileadmin/introduction/images/content/content-menu-sitemap-pages.png
fileadmin/introduction/images/content/content-menu-thumbnail.png
fileadmin/introduction/images/content/content-special-div.png
fileadmin/introduction/images/content/content-special-html.png
fileadmin/introduction/images/content/content-special-shortcut.png
fileadmin/introduction/images/content/content-special-uploads.png
fileadmin/introduction/images/content/content-tab.png
fileadmin/introduction/images/content/content-table.png
fileadmin/introduction/images/content/content-text-columns.png
fileadmin/introduction/images/content/content-text-teaser.png
fileadmin/introduction/images/content/content-textmedia.png
fileadmin/introduction/images/content/content-textpic.png
fileadmin/introduction/images/customizing/editor-shows-typo3-fluid.png
fileadmin/introduction/images/customizing/extbase.png
fileadmin/introduction/images/customizing/extensionbuilder.png
fileadmin/introduction/images/customizing/extensionmanager.png
fileadmin/introduction/images/features/ease-of-use.png
fileadmin/introduction/images/features/front-end-editing.png
fileadmin/introduction/images/features/granular-front-end-and-back-end-access-rights.png
fileadmin/introduction/images/features/multi-langauge-multi-domain.png
fileadmin/introduction/images/features/no-front-end-design-constraints.png
fileadmin/introduction/images/features/workspaces.png
fileadmin/introduction/images/map.png
fileadmin/introduction/images/streets/adrian-207619.jpg
fileadmin/introduction/images/streets/felix-russell-saw-182331.jpg
fileadmin/introduction/images/streets/geran-de-klerk-136351.jpg
fileadmin/introduction/images/streets/kimon-maritz-193428.jpg
fileadmin/introduction/images/streets/nikita-maru-70928.jpg
fileadmin/introduction/images/streets/richard-nolan-157476.jpg
fileadmin/introduction/images/typo3-book-template-tools.png
fileadmin/introduction/images/typo3-composing-backend-all.png
fileadmin/introduction/images/typo3-composing-backend-overview.png
fileadmin/introduction/youtube/evolution_of_the_typo3_ecosystem_-_mathias_schreiber____fabian_stein.youtube
fileadmin/introduction/youtube/typo3_-_2020.youtube
fileadmin/introduction/youtube/typo3_-_still_here.youtube
fileadmin/introduction/youtube/what_is_typo3_.youtube```

**Comment by NeoBlack** [comment] 2018-09-27 09:17
I can confirm the issue, iirc the problem is, that the filenames in `Initialisation/data.xml.files/*` not matching the referenced hashes in `Initialisation/data.xml` file.
I have no idea how to fix this. maybe @lolli42 can help because he updated the files before.

**Comment by maddy2101** [comment] 2018-09-27 10:42
typo3_console seems to be involved here. I installed the package purely with EM in BE, had no issues. The hint with the console comes from Olly, he used https://composer.typo3.org/.

**Comment by NeoBlack** [comment] 2018-09-27 10:45
I did a composer install with this composer.json file:

`{
    "name": "neoblack/t3test",
    "type": "project",
    "require": {
        "typo3/minimal": "9.4.0",
        "helhum/dotenv-connector": "^1.1",
        "typo3/cms-introduction": "^3.1"
    },
    "extra": {
        "typo3/cms": {
            "web-dir": "Web"
        }
    },
    "authors": [
        {
            "name": "Frank Naegler",
            "email": "frank.naegler@typo3.org"
        }
    ]
}`

activate / install the package in extensionmanager, no console.

**Comment by maddy2101** [comment] 2018-09-27 10:49
but minimal package? I was on master, both for TYPO3 and typo3/cms-introduction. While the intropackage master === 3.1.1, the core might have any influence? Just wildly guessing here.

**Comment by NeoBlack** [comment] 2018-09-27 10:52
Olli ask for TYPO3 v9.4.0 that's the reason why i tests with 9.4 minimal. anyway I think the problem ist identified: filenames and reference in data.xml don't match. Maybe I am wrong, but I guess the hashes should be identical, or not?

**Comment by ohader** [comment] 2018-09-27 18:05
Happens in Composer mode only, typo3-console is not an issue here.
When using Composer, temporary folders are created outside the `public/` path - due to https://review.typo3.org/#/c/57241/ files are copied to a wrong location or not at all or lead to an exception (depending on OS being used).

**Comment by ohader** [comment] 2018-09-27 18:15
https://review.typo3.org/#/c/58415/

**Comment by lolli42** [comment] 2018-10-01 10:39
patch has been merged to core master, so i guess this issue is solved. will close it.

**Closed by lolli42** 2018-10-01 10:39 UTC
