### ISSUE TITLE
Style the "To top" button

### ISSUE THREAD

**Issue by linawolf** [FriendsOfTYPO3/introduction#70] opened 2021-11-14 10:41 UTC
It would be nice if it had a styling. Now it is only a linked text

**Comment by gilbertsoft** [comment] 2021-11-14 11:24
@linawolf that's with BP 12 I guess?

**Comment by gilbertsoft** [comment] 2021-11-14 12:50
Mmh, not able to reproduce

![grafik](https://user-images.githubusercontent.com/25326036/141681771-39a9f064-180a-44d2-b919-70e0578e7151.png)

**Comment by linawolf** [comment] 2021-11-14 13:30
I am talking about the button that appears, when you use the flag `Append with Link to Top of Page[linkToTop]`  in the settings of a tt_content element.

![image](https://user-images.githubusercontent.com/48202465/141683274-464f2ade-45ab-48d4-a17d-56eb993789a0.png)

**Comment by gilbertsoft** [comment] 2022-01-14 13:59
That's finally a topic for https://github.com/benjaminkott/bootstrap_package/. It does imho not make sense to provide a different configuration here. I'm going to close this issue here for now.

**Closed by gilbertsoft** 2022-01-14 13:59 UTC
Labels: wontfix
