### ISSUE TITLE
Install of intro package not completed ...

### ISSUE THREAD

**Issue by JuergenHeym** [FriendsOfTYPO3/introduction#18] opened 2018-10-03 16:26 UTC
- typo3 v9.5.0
- clean package install
- select download predefined packages list on install
- select intro package

It starts downloading boostrap package and intro package 4.0.1.
Bootstrap package ist installed properly.
Intro package not. 
Get relatively fast a gray main window. Waited for a long time. Nothing changes.

Went to extension manager.
Deactivated intro packe.
Activated intro package.
Now it installs properly.

But ...
Not selecting intro package during first install, but installing manually via extension manager works fine.

**Comment by sebkln** [comment] 2018-10-07 19:09
I can confirm this. Loaded preconfigured distribution 'Official Introduction Package' in a fresh TYPO3 9.5 installation.

Using the 'install' button, the extensions `bootstrap_package` and `introduction` both get downloaded and installed, but the right column of the Backend will stay empty/gray after completion.

The whole page tree of the introduction package is missing after this (first) installation process. When you install EXT:introduction a second time, the page tree is added.

**Comment by jonathanheilmann** [comment] 2018-10-18 15:19
I can confirm this, too. But sadly I'm not able to add the page tree on a second EXT:introduction installation. The right window is going gray and nothing happens after installation.

**Comment by zeichensatz** [comment] 2018-12-18 17:02
I can confirm this with a clean install under TYPO3 9.5.3.

**Comment by springm** [comment] 2019-01-03 21:03
Same here. It took me a while to accept that it was not my mishandling...

**Comment by ohader** [comment] 2021-01-19 11:46
This might happen when running with a low PHP `max_execution_time`. For some/most Linux distributions this might be `30` seconds - and therefore it's a valid use case that should be considered - probably by the TYPO3 core.

**Comment by chris299** [comment] 2021-04-26 14:14
at my end it was related to the memory limit: the recommenced 128M were not sufficient according to the httpd error-log.
after increasing it to 164M it worked for me after installing, removing and installing again the intro package  through the browser

**Comment by gilbertsoft** [comment] 2023-08-15 21:50
The recommended memory limit for PHP is 256M since version 9.5 and a lower value looks to be the cause here. So I'm going to close this issue for now.

**Closed by gilbertsoft** 2023-08-15 21:50 UTC
Labels: enhancement, confirmed
